# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5c563f23073feb6ffb918d33523d95657221c5e5a0f01648543a10d2b7ecf233c7137c44ed294f149787e6b622016993757088659a9ffed2fa55885a0c770f

test:
  secret_key_base: 841212d25825f9272a137c6d40a2da8958938dccb18549f24d1c1b8eb80cdab1cfa87bd9e29639f3885dc1355ee83d6cd958a1e9f46b8ae0202f1b52fdf53c8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
